"""Initial migration

Revision ID: 550f7438affd
Revises: a3408a535c66
Create Date: 2025-05-22 00:00:20.859010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f7438affd'
down_revision = 'a3408a535c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_promotion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promotion_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_id')
        batch_op.drop_column('promotion_price')
        batch_op.drop_column('is_promotion')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('stock')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
